name = "twilight-haze-d33b"
main = "worker.js"
compatibility_date = "2025-11-01"

kv_namespaces = [
  { binding = "HUMAIN_DATA", id = "979fdfba036443c484c86f543106e88a" }
]

[vars]
OPENAI_API_KEY = "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"
